spring:
  application:
    name: product
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
debug: true
