spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    driver-class-name: org.postgresql.Driver
app:
  jwt:
    signing-key: AbCdEfGhIjKlMnOpQrStUvWxYz1234567890+AbCdEfGhIjKlmNoPqRsTu
    refresh-signing-key: AbCdEfGhIjKlMnOpQrStUvWxYz1234567890+AbCdEfGhIjKlmNoPqRsTu
    access-token-expiration: 900000
    refresh-token-expiration: 604800000
server:
  port: 8080